# Change these first
owner: imap-fi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sivusto
    url: https://imap.fi
  - name: Palvelun API
    url: https://api.imap.fi/heartbeat
  - name: IMAP (viestien vastaanottaminen)
    check: "tcp-ping"
    url: server.imap.fi
    port: 143
  - name: SMTP (viestien lähettäminen)
    check: "tcp-ping"
    url: server.imap.fi
    port: 587
  - name: Webmail
    url: https://mail.imap.fi

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.imap.fi
  favicon: https://imap.fi/favicon.png
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/95940610?s=400&u=7d5835ff20b9769ffe79d26138585f444a3b106b&v=4
  name: imap.fi - tilannehuone
  introTitle: "**imap.fi** on suomalainen sähköpostipalvelu."
  introMessage: Katselet tällä hetkellä palvelujemme tilannetta tilannehuoneesamme.
  navbar:
    - title: Status
      href: /
    - title: Sivusto
      href: https://imap.fi/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: Aktiiviset virheet
  allSystemsOperational: Kaikki palvelut toimivat
  incidentReport: "Virheen #$NUMBER raportti →"
  activeIncidentSummary: Avattu $DATE $POSTS:llä julkaisulla
  incidentTitle: Virheen numero $NUMBER tiedot
  incidentDetails: Virheen tiedot
  incidentFixed: Korjattu
  incidentOngoing: Käynnissä
  incidentOpenedAt: Avattu
  incidentClosedAt: Suljettu
  incidentSubscribe: Tilaa päivitykset
  incidentViewOnGitHub: Katsele GitHubissa
  incidentCommentSummary: Julkaistu $DATE kirjoittajana $AUTHOR
  incidentBack: ← Palaa kaikkiin virheisiin
  pastIncidents: Edelliset virheet
  pastIncidentsResolved: Korjattu $MINUTES minuutissa $POSTS:llä vastauksella
  liveStatus: Reaaliaikainen tilanne
  overallUptime: "Kokonaispäälläoloaika: $UPTIME"
  overallUptimeTitle: Kokonaispäälläoloaika
  averageResponseTime: "Keskimääräinen vastausaika: $TIMEms"
  averageResponseTimeTitle: Keskimääräinen vastausaika
  sevelDayResponseTime: 7-päivän vastausaika
  responseTimeMs: Vastausaika (ms)
  up: Päällä
  down: Alhaalla
  degraded: Heikentynyt
  ms: ms
  loading: Ladataan
  navGitHub: GitHub
  footer: Tämä sivu on [avoimen lähdekoodin]($REPO), moottorina [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Nopeusrajoitus saavutettu
  rateLimitExceededIntro: Olet saavuttanut tunnittaisen kyselyrajan, jotenka joudut odottamaan ennen kuin pääset taas vierailemaan sivustolla. Vaihtoehtoisesti voit lisätä GitHub Personal Access Tokenin jatkaaksesi tämän sivuston käyttöä.
  rateLimitExceededWhatDoesErrorMean: Mitä tämä virhe tarkoittaa?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: Kuinka voin korjata tämän?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Opi Personal Access Tokenin generointi
  rateLimitExceededHasSet: Sinulla on personal access token asetettu.
  rateLimitExceededRemoveToken: Poista token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Kopioi ja liitä tokenisi
  rateLimitExceededSaveToken: Tallenna token
  errorTitle: Ilmeni virhe.
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: Voit kokeilla uudestaan muutaman minuutin kuluttua.
  errorHome: Mene etusivulle
  pastScheduledMaintenance: Past Scheduled Maintenance
  scheduledMaintenance: Scheduled Maintenance
  scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
  scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
  startedAt: Alkanut
  startsAt: Alkaa
  duration: Kestää
  durationMin: $DURATION minuuttia
  incidentCompleted: Suoritettu
  incidentScheduled: Ajastettu
