# Change these first
owner: imap-fi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Sivusto
    url: https://imap.fi
  - name: Palvelun API
    url: https://api.imap.fi
  - name: IMAP (viestien vastaanottaminen)
    check: "tcp-ping"
    url: server.imap.fi
    port: 143
  - name: SMTP (viestien lähettäminen)
    check: "tcp-ping"
    url: server.imap.fi
    port: 587
  - name: Webmail
    url: https://mail.imap.fi

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.imap.fi
  favicon: https://imap.fi/favicon.png
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/95940610?s=400&u=7d5835ff20b9769ffe79d26138585f444a3b106b&v=4
  name: imap.fi - tilannehuone
  introTitle: "**imap.fi** on suomalainen sähköpostipalvelu."
  introMessage: Katselet tällä hetkellä palvelujemme tilannetta tilannehuoneesamme.
  navbar:
    - title: Status
      href: /
    - title: Sivusto
      href: https://imap.fi/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
